// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNzWiUVOER4ZJANYULWgq3xniFfITe_94',
    appId: '1:1029008051084:web:77533b47177ea2e30924a9',
    messagingSenderId: '1029008051084',
    projectId: 'todo-app-18310',
    authDomain: 'todo-app-18310.firebaseapp.com',
    storageBucket: 'todo-app-18310.appspot.com',
    measurementId: 'G-CKJJSXR9R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NDb-F_QwTSzgLYFD45uaeKfc4BPQg1o',
    appId: '1:1029008051084:android:2071e977d5d085830924a9',
    messagingSenderId: '1029008051084',
    projectId: 'todo-app-18310',
    storageBucket: 'todo-app-18310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCABF5yrY_y9S7buf7bisZAQaAJCSFnWi0',
    appId: '1:1029008051084:ios:f5f0701313481a360924a9',
    messagingSenderId: '1029008051084',
    projectId: 'todo-app-18310',
    storageBucket: 'todo-app-18310.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCABF5yrY_y9S7buf7bisZAQaAJCSFnWi0',
    appId: '1:1029008051084:ios:e7637f61f6267c5a0924a9',
    messagingSenderId: '1029008051084',
    projectId: 'todo-app-18310',
    storageBucket: 'todo-app-18310.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
